These scripts are used to analyse global floods.

* Compute files
- _compute_C_over_Q_: look at grid cell (0.5x0.5) containing dams and divide the average annual inflow by the storage capacity of dams. This gives an indication of which dams are run-of-the-river dams and will not influence daily discharge significantly.

- _compute_dam_cumulative_capacity_: for all grid cell, the cumulative storage capacity of dams located upstream is computed.

- _compute_divide_river_network_: Classify every grid cell as being above, below, between or not influeced by global dams.

- _compute_flood_area_basins_: for 14 catchments, analyse the annual maximum flooded areas and annaul flood occurance for grid cells above, between, and below dams.

- _compute_population_exposure_0.5deg_: estimation of the global population exposure to global flood using the original 0.5 resolution data.

- _compute_population_exposure_v2_: This script annually assess the number of people exposed to river flood. This uses the original resolution data (0.5 degree). For the population data, either a static 2010 population file or the yearly ssp2 predicion can be used. 

- _compute_return_future_v2_: calculate the 100-year extreme discharge in every grid cell by fitting a gumbel distribution to extreme discharge.

- _compute_return_period_baseline_: calculate the historical 100-year annual extreme discharge that is used to identify flood event.

- _compute_100_y_flood_occurence.r_: The frequency of the historical 100-y discharge is evaluated.

- _compute_flood_area_basins_downscaled.r_:using the downscaled flood plain water heigh, for several catchment this script evaluate the maximum flooded area above, below, and between dams. Flood occurence is also reported using originak 0.5degree resolution discharge.

* Downscale files
- _downscale_annual_fld_depth_: Every year, for all 0.5 x 0.5 grid cell where the historicaly 100-year discharge was excceded by the annual extreme discharge, the maximum flood depth is extracted and a "map" of the maximum flood depth for the year is constructed. This file will be downscaled to 0.005 later.

- _downscale_population_exposure_: Using the downscaled population and flood depth files (0.005 degree), population exposure to flood is computed.

- _downscale_0.5def_file.r_: Original grid ell position relativve to dams, grid cell number are downscaled to the 0.005 degree resolution

- _downscale_validation_fld_depth.r_: This script systematically create a maximum flooded depth annually. These files are then typically downscaled and then run into the check_downscaled.r algorithm.

* Other file
- _check_downscaled.r_: Compare the maximum flooded depth of the 0.5 resolution data with what is obtained after downscale

* Local script
These scripts are used on a personal computer to further analyse datasets and generate final graphs and tables.
** population
- _ssp_exposure_: Generate time-series of population exposure to river flood. This uses the original 0.5x0.5 degree resolution file and ssp2 population

- _population_exposure_ts_: Generate time-series of population exposure to river flood. This uses the original 0.5x0.5 degree resolution and 2010 year population.

- _downscaled_population_exposure_: Generate time-series of population exposure to river flood. This uses the downscaled 0.005x0.005 degree resolution file and 2010 population.

** downscale
- _allocate-country_: This file is used to associate each 0.005x0.005 grid-cell with a country.

** global
- _global_rcp26_rev_: create the global maps displaying the evoluation of the historical 100-year extreme discharge in the future with and without dams for rcp 2.6.

- _global_rcp60_rev_: create the global maps displaying the evoluation of the historical 100-year extreme discharge in the future with and without dams for rcp 6.0.
