The scripts and models described here were used in the work entitled: "Role of dams in reducing global flood exposure under climate change" by Boulange et al., (2020). First the setup to couple the H08 and CaMa-Flood models is explained. Next, scripts used for the data analysis are described. The third section contains script to downscale important datasets. The last section contains scripts used to generate figures and tables.
* Global models setup
** H08
The initial simulations using the H08 model are performed following the method described in the H08 manual with the following caveats:
1. The  river network needs to be identical to that of CaMa-Flood.
2. As a result, the locations of dams need to be adjusted in accordance to CaMa-Flood river network
3. Last, output files need to be stored as _little endian_ (this can be done after as a post process, after running the initial simulation but it is simpler to do it from the beginning)
** CaMa-Flood
*** Input files
For CaMa-Flood to consider dams, few extra inputs are necessary:
1. Dam location: To access this file, the path is currently hardcoded into the source code and may need to be modified. The format of the file is identical to that of the H08 model but endianess (_little_) may need to be changed. The path for this file needs to be define in the following files: calc_rivout.f, calc_fldout.f
2. Discharge: Similar to above, the path to access the daily discharge produced by H08 is hardcoded, the format is identical to that of H08 but endianess need to be "little". The path to daily river discharge need to be updated in the following files: calc_rivout.f, calc_fldout.f
Note that only the ".F" files need to be edited, the make file first convert those to ".f90" files and then to the final binary. 
- Important! Although not always indicated by the above mentioned flag, the OMP statements have to be edited! Here is an example:
  - Original: !$OMP THREADPRIVATE   (JSEQ, DSLOPE, DAREA, DFLW, DOUT_PRE, DFLW_PRE, DFLW_IMP)
  - Modified: !$OMP THREADPRIVATE   (JSEQ, DSLOPE, DAREA, DFLW, DOUT_PRE, DFLW_PRE, DFLW_IMP, IX, IY, IH08)
OMP is used to speedup loop excecution using multiple cores; if it disable, then no edit is necessary.

*** Source code
First, my edits in the original source code are always surrounded by "!! edit Julien" and "end edit julien" so by looking for those strings in the source files (".F"), it is relatively easy to identify all changes.
- Inventory of modified files:
  1. in src/ calc_damout.F, calc_fldout.F, calc_rivout.F, calc_stonxt.F, control_out.F, control_phys.F, init_cond.F
  2. in mod/ mod_input.F mod_prog.F
  3. in lib/ -
- 

*** Key edits
Here I briefly describe the key edits in the majors source code files.
1. mod_input.F: new parameter and log file definition
2. mod_prog.F: Storage for dams
3. init_cond.F: Initial condition for reservoir storage
4. calc_rivout.F: Read dam locations, if a dam is present in the grid cell, discharge is swapped with that of the H08 model.
5. calc_fldout.F: Read the dam location file, if there is a dam there is no flow possible from the floodplain (reset to 0).
6. calc_stonxt.F: Edit to correctly compute the water balance
7. control_phys.F: Minor change to which parameters are exported to the module. The goal here is to be able to get the day of simulation for the curent time step to open the corrct daily discharge file.
8. calc_damout.F: not used by the model

*** Important variables
I have  introduced new variables (mainly related to dam storage), but also needed to access variales defined in CaMa-Flood but not used in specific modules.
1. D2SAVE
   - new: yes
   - Define in: mod_prog.F
   - Use in: calc_rivout.F, calc_stonxt.F, init_cond.F
2. D2RESSTO_OUT
   - new: yes
   - Define in: mod_prog.F
   - Use in: calc_rivout.F, calc_stonxt.F, init_cond.F
3. LOGDAM
   - new: yes
   - Define in: mod_input.F
   - Use in: ?
4. CLDOUT
   - new: yes
   - Define in: mod_input.F
   - Use in: ?
5. IX
   - new: no
   - Define in: no
   - Use in: almost all files
6. IY
   - new: no
   - Define in: no
   - Use in: almost all files
7. r1tmp
   - new: yes
   - Define in: no
   - Use in: calc_fldout.F, calc_damout.F, calc_rivout.F, calc_stonxt.F
8. i0l
   - new: yes
   - Define in: no
   - Use in: calc_fldout.F, calc_stonxt.F, cal_damout.F, calc_rivout.F
9. IH08
   - new: yes
   - Define in: no
   - Use in: calc_fldout.F, calc_damout.F, calc_stonxt.F, control_out.F, calc_rivout.F, calc_fldstg.F
10. IT
    - new: no
    - Define in: control_phys.F
    - Use in: control_phys.F, calc_rivout.F

*** Possible improvements
- Read the dam location only once at the beginning of the simulation

* Compute files
- _compute_C_over_Q_: look at grid cell (0.5x0.5) containing dams and divide the average annual inflow by the storage capacity of dams. This gives an indication of which dams are run-of-the-river dams and will not influence daily discharge significantly.

- _compute_dam_cumulative_capacity_: for all grid cell, the cumulative storage capacity of dams located upstream is computed.

- _compute_divide_river_network_: Classify every grid cell as being above, below, between or not influeced by global dams.

- _compute_flood_area_basins_: for 14 catchments, analyse the annual maximum flooded areas and annaul flood occurance for grid cells above, between, and below dams.

- _compute_population_exposure_0.5deg_: estimation of the global population exposure to global flood using the original 0.5 resolution data.

- _compute_population_exposure_v2_: This script annually assess the number of people exposed to river flood. This uses the original resolution data (0.5 degree). For the population data, either a static 2010 population file or the yearly ssp2 predicion can be used. 

- _compute_return_future_v2_: calculate the 100-year extreme discharge in every grid cell by fitting a gumbel distribution to extreme discharge.

- _compute_return_period_baseline_: calculate the historical 100-year annual extreme discharge that is used to identify flood event.

- _compute_100_y_flood_occurence.r_: The frequency of the historical 100-y discharge is evaluated.

- _compute_flood_area_basins_downscaled.r_:using the downscaled flood plain water heigh, for several catchment this script evaluate the maximum flooded area above, below, and between dams. Flood occurence is also reported using originak 0.5degree resolution discharge.

* Downscale files
- _downscale_annual_fld_depth_: Every year, for all 0.5 x 0.5 grid cell where the historicaly 100-year discharge was excceded by the annual extreme discharge, the maximum flood depth is extracted and a "map" of the maximum flood depth for the year is constructed. This file will be downscaled to 0.005 later.

- _downscale_population_exposure_: Using the downscaled population and flood depth files (0.005 degree), population exposure to flood is computed.

- _downscale_0.5def_file.r_: Original grid ell position relativve to dams, grid cell number are downscaled to the 0.005 degree resolution

- _downscale_validation_fld_depth.r_: This script systematically create a maximum flooded depth annually. These files are then typically downscaled and then run into the check_downscaled.r algorithm.

* Other file
- _check_downscaled.r_: Compare the maximum flooded depth of the 0.5 resolution data with what is obtained after downscale

* Local script
These scripts are used on a personal computer to further analyse datasets and generate final graphs and tables.
** population
- _ssp_exposure_: Generate time-series of population exposure to river flood. This uses the original 0.5x0.5 degree resolution file and ssp2 population

- _population_exposure_ts_: Generate time-series of population exposure to river flood. This uses the original 0.5x0.5 degree resolution and 2010 year population.

- _downscaled_population_exposure_: Generate time-series of population exposure to river flood. This uses the downscaled 0.005x0.005 degree resolution file and 2010 population.

** downscale
- _allocate-country_: This file is used to associate each 0.005x0.005 grid-cell with a country.

** global
- _global_rcp26_rev_: create the global maps displaying the evoluation of the historical 100-year extreme discharge in the future with and without dams for rcp 2.6.

- _global_rcp60_rev_: create the global maps displaying the evoluation of the historical 100-year extreme discharge in the future with and without dams for rcp 6.0.
